### PR TITLE
feat: remove overflow warning

### PR DESCRIPTION
**Pull request by gbprod**
This PR removes the detection of lines not following the [50/72 rule](https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting).

After a lot of discussions and thinking, I've decided that this rule should not be bundled with the tree-sitter parser.

Main reasons are:

- This is annoying for users who don't follow this rule and it's not easy to disable it ;
- This is more the job of a linter like [gitlint](https://github.com/jorisroovers/gitlint) or [commitlint](https://commitlint.js.org/) or query;
- This is not a syntax rule, but a convention rule
- I prefer to keep the parser as simple as possible
- After merging this PR, it will be easy to recreate this behavior using a query:

```query
((subject) @comment.error
  (#vim-match? @comment.error ".\{50,}")
  (#offset! @comment.error 0 50 0 0))

((message_line) @comment.error
  (#vim-match? @comment.error ".\{72,}")
  (#offset! @comment.error 0 72 0 0))
```

References:
 
 - https://github.com/gbprod/tree-sitter-gitcommit/issues/46
 - https://www.reddit.com/r/neovim/comments/1cm5zir/question_should_i_commit_summaries_not_following/

### CODE REVIEW

**Comment by Flimm** [comment]
Even though I miss the old behaviour, I agree with this decision. I think your reasoning is sound. Thank you for introducing me to `gitlint`! For the lurkers, in order to ensure gitlint checks that the title line does not exceed 50 characters, add these lines to your `.gitlint` configuration file:

    [title-max-length]
    line-length=50

**Comment by cameronr** [comment]
> ```
> ((subject) @comment.error
>   (#vim-match? @comment.error ".\{50,}")
>   (#offset! @comment.error 0 50 0 0))
> 
> ((message_line) @comment.error
>   (#vim-match? @comment.error ".\{72,}")
>   (#offset! @comment.error 0 72 0 0))
> ```

Could you share how to use the above? I can paste it into `:EditQuery` but it doesn't seem to highlight anything. I liked the previous behavior and am interested in reproducing it.

Thanks!

**Comment by gbprod** [comment]
You should use `:TSEditQueryUserAfter highlight gitcommit` and add :

```
;; extends

((subject) @comment.error
  (#vim-match? @comment.error ".\{50,}")
  (#offset! @comment.error 0 50 0 0))

((message_line) @comment.error
  (#vim-match? @comment.error ".\{72,}")
  (#offset! @comment.error 0 72 0 0))
```

**Comment by cameronr** [comment]
Thanks for the quick response. Unfortunately, I still must be missing something :( I added the above (saved and quit) but i'm still not seeing any highlighting. This is what I see when i run `git commit` and type in a subject and message line that are too long:

Screenshot 2024-08-13 at 17 20 39

Any help is greatly appreciated!

**Comment by gbprod** [comment]
What's your highlight for `@comment.error`? Can you share the result of `hi @comment.error`?
What's your color scheme?

**Comment by cameronr** [comment]
`@comment.error` is a red color:

```viml
:hi @comment.error
@comment.error xxx guifg=#db4b4b
```

I'm using `folke/tokyonight` with the `night` style. Trying other color schemes in a live preview doesn't highlight the error either. This is on nvim 0.10.1 if that's relevant.

**Comment by cameronr** [comment]
In case it's helpful for anyone later, it works if it's `nvim/queries` folder rather than `nvim/after/queries`:

` ~/.config/nvim/queries/gitcommit/highlights.scm`

Not sure why it doesn't work when put in the after directory...

**Comment by nickjj** [comment]
Hi,

I really miss this behavior, the PR mentions it's easy to add it back individually with:

```
((subject) @comment.error
  (#vim-match? @comment.error ".\{50,}")
  (#offset! @comment.error 0 50 0 0))

((message_line) @comment.error
  (#vim-match? @comment.error ".\{72,}")
  (#offset! @comment.error 0 72 0 0))
```

But where would this go to have it always applied and not have to think about it?

I'm using LazyVim if it helps.

This is what my current Treesitter plugin config looks like:

```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      -- Add custom treesitters not present by default in LazyVim.
      vim.list_extend(opts.ensure_installed, {
        "csv",
        "dockerfile",
        "go",
        "helm",
        "liquid",
        "nginx",
        "ruby",
        "terraform",
        "toml",
      })
    end,
  },
```

**Comment by gbprod** [comment]
I think you did the right thing. Maybe you can adds `gitcommit` in the `ensure_installed` list (or use this extra : https://www.lazyvim.org/extras/lang/git)

 `; extends` is required at the begining of the file.

If it stills not work, can your share an `:InspectTree` result ?

**Pull request merged**
