### PR TITLE
docs: add supported locale list to readme

### LINKED ISSUE #9: List of languages supported by the parser
Given that this project's main selling point is the support for generic languages (non-English), I think it's worth a mention on the project `README.md`.\
I think we can do a list, similar to [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter/#supported-languages), (not programming languages but for languages "English", "Russian", "Chinese (Simplified)", etc..)

This way, users know at a glance whether their own language is supported by your parser or not.

### PR DESCRIPTION
**Pull request by thatlittleboy**
Fixes #9 

---

Logs:
* I just ran Google translate on the various text in `grammar.js`, please let me know if the list of languages I've compiled is inaccurate.

### CODE REVIEW

**Comment by gbprod** [comment]
Thanks for that!

Can you check if it matchs with git supported languages (https://github.com/git/git/tree/master/po) ans order languages alphabetically ?

**Comment by thatlittleboy** [comment]
Yep will do :) Will push the updates up soon

**Comment by thatlittleboy** [comment]
I took reference from the "Please enter the commit message ..." line, and compared it against git's supported locales (the link u shared).

Currently, I think we're missing:
* bg (Bulgarian)
* is (Icelandic)

It is possible that the other languages are not completely supported in our `grammar.js` as well, since I only based it on this one line. But this should be good enough for now.

I also took the liberty to sort the translations inside `grammar.js` to this particular README order (i.e., alphabetical, except for English at the top) for this one line. I think it makes it easier to keep track of whether a particular line's translation is supported or not, but if you want me to revert this change, I can do so.

**Comment by gbprod** [comment]
Icelandic is empty and it seems that I've missed some Bulgarian translations :sweat_smile: , I create an issue

**Comment by gbprod** [comment]
Can you add a link to https://github.com/git/git/tree/master/po in the README ? 

Thanks

**Comment by thatlittleboy** [comment]
Done!

**Comment by gbprod** [comment]
Thanks!

**Pull request merged**
